version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  quarkus:
    depends_on: [mongodb]
    image: quarkus:v1
    ports: 
      - 8080:8080
    build:
      context: .  
      dockerfile: src/main/docker/Dockerfile.jvm    
volumes:
  mongodb_data_container:
